version: "3.9"  # optional since v1.27.0
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    